version: '3'
services:
    gateway-proxy:
        build: ./proxy-gateway
        restart: always
        hostname: gateway
        env_file:
            - .env
        ports:
            - "3000:3000"
        links:
            - rabbitmq
        depends_on:
            - rabbitmq
       
      
    publisher-service:
        build: ./publisher-service
        restart: always
        hostname: task
        env_file:
            - .env
        links:
            - mongo
            - rabbitmq
        depends_on:
            - rabbitmq
            - mongo

    game-service:
        build: ./game-service
        restart: always
        hostname: task
        env_file:
            - .env
        links:
            - mongo
            - rabbitmq
        depends_on:
            - rabbitmq
            - mongo
       

    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:3.6.6-management"
        tty: true
        volumes:
            - ./rabbitmq-data:/var/lib/rabbitmq/mnesia
            - ./rabbitmq-data/logs:/var/log/rabbitmq
        ports:
            - "5672:15672"
        expose:
        # Opens port 3306 on the container
            - "15672"
        healthcheck:
            test: ["CMD", "nc", "-z", "localhost", "15672"]
            interval: 5s
            timeout: 15s
            retries: 10
        hostname: rabbitmq
       

    mongo:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - ./data/dev/mongo:/data/db
        ports:
            - "27017:27017"
       

  
  